### ISSUE TITLE
Error with 'npm run scope'

### ISSUE THREAD

**Issue by julienvibert** [aertslab/SCope#221] opened 2019-11-26 16:08 UTC
Hi,

I tried using SCope on the website 'http://scope.aertslab.org/' but the site doesn't seem to be working (neither its mirror)..

Then I have followed the instructions to install SCope with Conda until 'npm install', however when I try 'npm run scope', I get the following error (here is my terminal screen):
`npm run scope

> SCope@1.7.2 scope /home/julien/repos/SCope
> node bin/launch.js

  /$$$$$$   /$$$$$$                               
 /$$__  $$ /$$__  $$                              
| $$  \__/| $$  \__/  /$$$$$$   /$$$$$$   /$$$$$$ 
|  $$$$$$ | $$       /$$__  $$ /$$__  $$ /$$__  $$
 \____  $$| $$      | $$  \ $$| $$  \ $$| $$$$$$$$
 /$$  \ $$| $$    $$| $$  | $$| $$  | $$| $$_____/
|  $$$$$$/|  $$$$$$/|  $$$$$$/| $$$$$$$/|  $$$$$$$
 \______/  \______/  \______/ | $$____/  \_______/
                              | $$                
                              | $$                
                              |__/                

-------- running settings --------
Running on Linux
Running in AWS: false
Running as daemon: false
Running in development mode: true
   *** please run in production mode except if it's for testing purposes.
----------------------------------

--------- sanity checks ----------
conda command found.
- Checking SCope Server...
scope-server command found.
- Checking SCope conda environment...
SCope Server is installed and activated!
- Checking tmux...
- Checking directories (assets)...
- Checking Apache configuration...
- Checking public host address...
----------------------------------

--------- running scope ----------
Starting SCope...
Starting SCope Server...
Starting SCope Client as Dev Server...
A SCope instance is running at http://127.0.0.1
----------------------------------

Open SCope in browser...

`

Then my browser opens at 'http://localhost:8080/' and I get this following message:
'localhost n'autorise pas la connexion' (localhost doesn't authorize connection)

What should I do to overcome this error?

Thank you for your help!

Best,

Julien

**Comment by dweemx** [comment] 2019-11-26 16:50
Hi @julienvibert,

Thanks for reaching out.

What do you mean by the [scope.aertslab.org](url) is not working ? You can't access the website ? or you can't upload a loom ? or ...

Regarding launching SCope locally, I cannot reproduce your error unfortunately. I tried a local fresh installation:
```
git clone https://github.com/aertslab/SCope
conda create -n scope_test 'python==3.6.2' 'nodejs>=9'
source activate scope_test
cd SCope/
npm install
```

then running SCope:
```
$ npm run scope
> SCope@1.7.2 scope ~/Documents/Test/SCope/local_launch/SCope
> node bin/launch.js

  /$$$$$$   /$$$$$$                               
 /$$__  $$ /$$__  $$                              
| $$  \__/| $$  \__/  /$$$$$$   /$$$$$$   /$$$$$$ 
|  $$$$$$ | $$       /$$__  $$ /$$__  $$ /$$__  $$
 \____  $$| $$      | $$  \ $$| $$  \ $$| $$$$$$$$
 /$$  \ $$| $$    $$| $$  | $$| $$  | $$| $$_____/
|  $$$$$$/|  $$$$$$/|  $$$$$$/| $$$$$$$/|  $$$$$$$
 \______/  \______/  \______/ | $$____/  \_______/
                              | $$                
                              | $$                
                              |__/                

-------- running settings --------
Running on Linux
Running in AWS: false
Running as daemon: false
Running in development mode: true
   *** please run in production mode except if it's for testing purposes.
----------------------------------

--------- sanity checks ----------
conda command found.
- Checking SCope Server...
scope-server command found.
- Checking SCope conda environment...
SCope Server is installed and activated!
- Checking tmux...
- Checking directories (assets)...
- Checking Apache configuration...
- Checking public host address...
----------------------------------

--------- running scope ----------
Starting SCope...
Starting SCope Server...
Starting SCope Client as Dev Server...
```
and **accessing it with the following URL: [http://localhost:55850/](http://localhost:55850/)**

Are you sure you have **Node v9** or greater installed ?

**Comment by dweemx** [comment] 2019-11-26 18:48
SCope currently uses unsecured WebSocket connections, It could be that your infrastructure do not allow these type of connections... Therefore could you try to test for this using [http://www.websocket.org/echo.html](http://www.websocket.org/echo.html).

By default, the local port of the local instance of SCope should be 55850.
Have you tried to access it in the browser using [http://localhost:55850/](http://localhost:55850/) ?

**Comment by julienvibert** [comment] 2019-11-27 08:29
Hi Max,

Thanks for your reply.
Indeed it seems that I can't have access to this type of connection..
I also tried with local port 55850 but I got the same error.
Maybe I should ask my IT administrators to resolve this.

Don't hesitate to tell me if you have other ideas.
Thanks a lot!

Best,
Julien

**Comment by dweemx** [comment] 2019-11-27 09:26
Yes, I think it's good idea to ask IT. Let us know if you worked it out with them :).
We are also considering moving towards `https` and `wss` but currently we have no ETA defined unfortunately.

**Comment by julienvibert** [comment] 2019-11-27 09:31
Thanks Max, I'll let you know if I work it out!
Best,
Julien

**Comment by julienvibert** [comment] 2019-11-28 15:52
Hi Max,
Sorry to bother you again, but I have contacted my IT department and they say they have tried but can't get access to either http://scope.aertslab.org or scope-mirror.aertslab.org, whichever machine or network they use: they are wondering if you have a problem on your websites at the moment?
Thank you for your help!
Best,
Julien

**Comment by dweemx** [comment] 2019-11-28 16:18
That's weird...
We don't have any problem at the moment. I'm accessing it now.
I also did a quick check using Website Planet: 
Everything is fine: [https://www.websiteplanet.com/webtools/down-or-not/](https://www.websiteplanet.com/webtools/down-or-not/)
![image](https://user-images.githubusercontent.com/16015936/69821041-d8843900-1202-11ea-8947-1ba5d97cd9e1.png)

**Comment by julienvibert** [comment] 2019-11-28 16:39
OK thanks!
That's strange for sure.
I noted something however, if I use this address (with https): https://scope-mirror.aertslab.org
I get redirected to the home page of the Aerts lab. Is it normal?
Best,
Julien

**Comment by dweemx** [comment] 2019-11-28 16:50
Generally, I was wondering if you could access unsecured websites ? (maybe that the main cause ?)
Thanks for reporting, indeed it shoudn't be redirected.

**Comment by julienvibert** [comment] 2019-11-28 17:00
No indeed I can't access unsecured (http) websites, neither http://scope.aertslab.org nor http://scope-mirror.aertslab.org.
I'm going to tell the IT department your answer and the fact that there is no problem with the websites on your side.
I'll get back to you if needed.
Thanks a lot again,
Julien

**Comment by MaybeJustJames** [comment] 2021-07-29 18:21
Hi @julienvibert,
The way SCope works will be fundamentally changing in the near future. As a result I'm wondering if you would be happy with me closing this issue. If it is still a problem for you we can leave it open until the change and reevaluate.

**Comment by julienvibert** [comment] 2021-07-30 06:58
Hi @MaybeJustJames ,
You can close the issue, thank you!
Best,
Julien

**Closed** 2021-07-30 07:25 UTC
